travis:
  secure:
    BINSTAR_TOKEN: iGOCc9oxaV0z2XxllYclcnTqgsg9Xu6SX9nX2EbTXIjob2q+uLulW0piQF2hWVTmrP8Wje0USOkDXds3ac9SQSaFGOW90x0YCgc0SvblRXorL15hLjzt6WOmYnPyG3P5ZZh31vY51jpO9VZmijvq+mIc7UpSqldAzVU5oKkSpG54AtDzsQVwYNH1fkrefkgJzXEmWTU9w4eZhW9vKjRRirgwzHcRZu8yZdYa8wjWYqCTnnAPMF1WmaGg7iVR76DGDALOsG1DQHH1WJv96wyMcn+z97vzm9Ho66WcuNV4qaII5UeP2nqHT7TDguu3zjatJ1mNZzWwm1jn+Wu6T/+nNKXnTnhVeotaUDmU+q4JFo29NdJhZ1vkid+YTjDOuS4WyyZChvoIrKfjTcAmZda0BOz4fCY134/Wg4TcxlPiZxIC8G8E+PTFn1mZh9xShe5ehPsGC3XhD0LqwOzuR/cMwEtUr9oW6XW7hL6st0BR/d+R+4+iv5U4FpNLFYVeVw138ua3KQbQIZIopnPqA3swugNEqLuB2Lft4OdBDu/BeQ7FhX5gmRvoD0EE2QC3nHaN+H60m1FOccA7dWKnsnWW3LR3r/kBi24uFE03M5+jzpTrw7o5L3VVlBgHgSwonR7ehadHiayy3bICMzAizOfWm6MaRpSrFBgW9I6KKUyz44Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
